/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StakingContract } from "./StakingContract";
export * as factories from "./factories";
export { StakingContract__factory } from "./factories/StakingContract__factory";
