/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as navhHackerNftSol from "./NAVHHackerNFT.sol";
export type { navhHackerNftSol };
import type * as sponsorGasPaymaster from "./SponsorGasPaymaster";
export type { sponsorGasPaymaster };
export type { PaymasterApplicationsRegistry } from "./PaymasterApplicationsRegistry";
export type { StakingContract } from "./StakingContract";
export type { XSuperhack } from "./XSuperhack";
